Add compareTo aliases
srknzl/bigdecimal.js pull request #90
Opened 2022-07-11 08:18 UTC by d-mon-

I created the PR for now until we figure out the new name for `equals`.

It might conflict with https://github.com/srknzl/bigdecimal.js/pull/82

fixes: [#73](https://github.com/srknzl/bigdecimal.js/issues/73)

2022-07-24 17:13 UTC, srknzl commented on test/compareTo.js
> -            if (test.result === 'errorThrown') {
I know compareToTestCases.json and some other json files does not include any "errorThrown" test cases, but can we keep this part just for consistency with other test codes? I want to be sure that if Java throws, our lib should also throw regardless of the method that is tested.

2022-07-24 17:16 UTC, srknzl commented on src/bigdecimal.ts
> +    greaterThan(val: any) {
Can you add return types to these methods?

2022-07-24 17:18 UTC, srknzl commented on test/equalsStrict.js
>      it('should calculate equals correctly', function () {
can you rename remaining "equals" texts to "equalsStrict" in this file? 


1. in it()
2. assertion message strings

2022-07-24 17:18 UTC, srknzl requested changes
Looks good overall except some minor things

2022-07-24 17:25 UTC, srknzl commented on src/bigdecimal.ts
> +     * new BigDecimal("2.00").divide(BigDecimal.valueOf(3), HALF_UP) which evaluates to 0.67.
This does not look good in the API documentation: 
<img width="834" alt="image" src="https://user-images.githubusercontent.com/32355782/180658913-98bff310-959a-44b6-bfc6-97f8874b6472.png">


We can put the code in backticks and add one or two line breaks

2022-08-10 20:00 UTC, srknzl commented
To think more, let's don't rush to merge this PR. Maybe we can come up with something better. Current implementation is ok though.

2022-08-10 20:01 UTC, srknzl commented
Maybe we can isolate "equals" part of this PR and merge the rest quickly.

2022-10-04 08:46 UTC, d-mon- commented
Included in https://github.com/srknzl/bigdecimal.js/pull/99

2022-10-04 08:46 UTC, closed without merging